# Generated by Django 5.2.6 on 2025-09-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_family'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_family__3fb736_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family',
        ),
        migrations.RemoveField(
            model_name='user',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱地址'),
        ),
    ]
