# Generated by Django 5.2.6 on 2025-09-04 02:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
        ('Family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='交易ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='金额')),
                ('type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='交易类型')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('wechat', '微信支付'), ('alipay', '支付宝'), ('card', '银行卡'), ('other', '其他')], max_length=20, verbose_name='支付方式')),
                ('date', models.DateTimeField(verbose_name='交易时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Category.category', verbose_name='分类')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Family.family', verbose_name='所属家庭')),
            ],
            options={
                'verbose_name': '交易',
                'verbose_name_plural': '交易',
                'db_table': 'transaction',
            },
        ),
    ]
