# Generated by Django 5.2.6 on 2025-09-04 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_transactions', to=settings.AUTH_USER_MODEL, verbose_name='关联成员'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='transaction_date_27f26b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['family', 'type'], name='transaction_family__5c24eb_idx'),
        ),
    ]
