# Generated by Django 5.2.6 on 2025-09-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Transaction', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_family__5c24eb_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='family',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='related_user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='Category.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_c453c0_idx'),
        ),
    ]
