# Generated by Django 4.1 on 2025-09-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='类型')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Family.family', verbose_name='所属家庭')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'category',
                'unique_together': {('name', 'parent', 'family')},
            },
        ),
    ]
