# Generated by Django 5.2.6 on 2025-09-04 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tag', '0001_initial'),
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tag.tag', verbose_name='标签')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.transaction', verbose_name='交易')),
            ],
            options={
                'verbose_name': '交易标签关联',
                'verbose_name_plural': '交易标签关联',
                'db_table': 'transaction_tag',
                'unique_together': {('transaction', 'tag')},
            },
        ),
    ]
