# Generated by Django 5.2.6 on 2025-09-05 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('self', '本人'), ('father', '父亲'), ('mother', '母亲'), ('son', '儿子'), ('daughter', '女儿'), ('husband', '丈夫'), ('wife', '妻子'), ('grandfather', '爷爷'), ('grandmother', '奶奶'), ('grandson', '孙子'), ('granddaughter', '孙女'), ('other', '其他')], max_length=20, verbose_name='关系')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('member', '普通成员')], max_length=10, verbose_name='角色')),
                ('family', models.ForeignKey(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, to='Family.family', verbose_name='家庭')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '家庭成员关系',
                'verbose_name_plural': '家庭成员关系',
                'db_table': 'family_members',
                'unique_together': {('family', 'user')},
            },
        ),
    ]
