# Generated by Django 4.1 on 2025-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(default='#808080', max_length=7, verbose_name='颜色')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
            },
        ),
    ]
