# Generated by Django 5.2.6 on 2025-09-04 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Family', '0001_initial'),
        ('Tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tag',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Family.family', verbose_name='所属家庭'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'family')},
        ),
    ]
