# Generated by Django 4.1 on 2025-09-03 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Family', '0001_initial'),
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='tag',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Family.family', verbose_name='所属家庭'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'family')},
        ),
    ]
