# Generated by Django 5.2.6 on 2025-09-05 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0001_initial'),
        ('Tag', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='family',
            field=models.ForeignKey(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, to='Family.family', verbose_name='所属家庭'),
        ),
    ]
