# Generated by Django 5.2.6 on 2025-09-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0003_alter_tag_creator_alter_tag_family'),
        ('Transaction', '0003_remove_transaction_transaction_family__5c24eb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='transaction',
            field=models.ForeignKey(db_column='transaction_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction.transaction', verbose_name='交易'),
        ),
    ]
